from app.domain.assets import (
    Asset,
    AssetOverview,
    AssetPosition,
    AssetTelemetry,
    AssetType,
)
from app.health.engine import health_engine


def make_asset(
    asset_id: str,
    name: str,
    asset_type: AssetType,
    manufacturer: str,
    model: str,
    position: tuple[float, float],
    measurements: dict[str, float | str | bool | None],
) -> AssetOverview:
    asset = Asset(
        id=asset_id,
        name=name,
        assetType=asset_type,
        siteId="PILBARA-IRON-MINE",
        manufacturer=manufacturer,
        model=model,
        position=AssetPosition(x=position[0], y=position[1], z=0),
    )
    telemetry = AssetTelemetry(
        assetId=asset_id,
        recordedAt="2026-06-05T08:10:00Z",
        source="fleet-telemetry",
        measurements=measurements,
    )

    return AssetOverview(
        asset=asset,
        health=health_engine.evaluate(asset, telemetry),
        telemetry=telemetry,
    )


class MockAssetRepository:
    def __init__(self) -> None:
        self._assets = [
            make_asset(
                "HT-07",
                "HT-07",
                AssetType.HAUL_TRUCK,
                "Caterpillar",
                "797F",
                (24, -4),
                {
                    "engine": "Running",
                    "operator": "M. Johnson",
                    "gps": "23.45S, 134.21E",
                    "task": "Hauling/Crusher",
                    "speedKph": 52,
                    "engineHours": 6240.2,
                    "ambientTemperatureC": 31.2,
                    "tireAgeHours": 428.0,
                    "tireLoadPercent": 92,
                    "usefulLifeHours": 1.2,
                    "payloadTonnes": 238,
                    "payloadCapacityTonnes": 220,
                    "frontLeftTireC": 94,
                    "frontRightTireC": 102,
                    "rearLeftTireC": 187,
                    "rearRightTireC": 141,
                    "frontLeftTirePsi": 98,
                    "frontRightTirePsi": 92,
                    "rearLeftTirePsi": 83,
                    "rearRightTirePsi": 90,
                },
            ),
            make_asset(
                "HT-04",
                "HT-04",
                AssetType.HAUL_TRUCK,
                "Komatsu",
                "930E",
                (-24, 30),
                {
                    "speedKph": 28.4,
                    "engineTempC": 91.2,
                    "ambientTemperatureC": 30.4,
                    "tireAgeHours": 384.0,
                    "payloadTonnes": 206,
                    "payloadCapacityTonnes": 220,
                    "fuelLevelPercent": 64,
                    "frontLeftTireC": 86,
                    "frontRightTireC": 88,
                    "rearLeftTireC": 89,
                    "rearRightTireC": 87,
                    "frontLeftTirePsi": 104,
                    "frontRightTirePsi": 103,
                    "rearLeftTirePsi": 102,
                    "rearRightTirePsi": 104,
                },
            ),
            make_asset(
                "HT-11",
                "HT-11",
                AssetType.HAUL_TRUCK,
                "Caterpillar",
                "793F",
                (2, -22),
                {
                    "speedKph": 47.9,
                    "engineTempC": 88.1,
                    "ambientTemperatureC": 32.8,
                    "tireAgeHours": 446.0,
                    "payloadTonnes": 224,
                    "payloadCapacityTonnes": 220,
                    "fuelLevelPercent": 51,
                    "frontLeftTireC": 98,
                    "frontRightTireC": 118,
                    "rearLeftTireC": 108,
                    "rearRightTireC": 102,
                    "frontLeftTirePsi": 96,
                    "frontRightTirePsi": 94,
                    "rearLeftTirePsi": 96,
                    "rearRightTirePsi": 95,
                },
            ),
            make_asset(
                "HT-15",
                "HT-15",
                AssetType.HAUL_TRUCK,
                "Liebherr",
                "T 284",
                (52, 10),
                {
                    "speedKph": 22.1,
                    "engineTempC": 84.6,
                    "ambientTemperatureC": 29.8,
                    "tireAgeHours": 362.0,
                    "payloadTonnes": 205,
                    "payloadCapacityTonnes": 220,
                    "fuelLevelPercent": 72,
                    "frontLeftTireC": 84,
                    "frontRightTireC": 83,
                    "rearLeftTireC": 86,
                    "rearRightTireC": 85,
                    "frontLeftTirePsi": 103,
                    "frontRightTirePsi": 102,
                    "rearLeftTirePsi": 104,
                    "rearRightTirePsi": 102,
                },
            ),
            make_asset(
                "EX-02",
                "EX-02",
                AssetType.EXCAVATOR,
                "Caterpillar",
                "6060",
                (0, 2),
                {"engineHours": 14288, "hydraulicPressureBar": 314, "swingRateRpm": 4.6, "bucketLoadTonnes": 43.2},
            ),
            make_asset(
                "EX-05",
                "EX-05",
                AssetType.EXCAVATOR,
                "Hitachi",
                "EX5600",
                (18, 24),
                {"engineHours": 11804, "hydraulicPressureBar": 302, "swingRateRpm": 4.1, "bucketLoadTonnes": 39.4},
            ),
            make_asset(
                "DR-01",
                "DR-01",
                AssetType.DRILL,
                "Epiroc",
                "Pit Viper 271",
                (34, 42),
                {"holeDepthMetres": 38.5, "bitPressureKn": 176, "rotationRpm": 92, "airPressureBar": 24.8},
            ),
            make_asset(
                "DZ-03",
                "DZ-03",
                AssetType.HAUL_TRUCK,
                "Komatsu",
                "930E",
                (-14, 10),
                {
                    "speedKph": 12.4,
                    "engineTempC": 79.9,
                    "ambientTemperatureC": 27.6,
                    "tireAgeHours": 316.0,
                    "payloadTonnes": 0,
                    "payloadCapacityTonnes": 220,
                    "fuelLevelPercent": 83,
                    "frontLeftTireC": 78,
                    "frontRightTireC": 76,
                    "rearLeftTireC": 79,
                    "rearRightTireC": 77,
                    "frontLeftTirePsi": 101,
                    "frontRightTirePsi": 102,
                    "rearLeftTirePsi": 100,
                    "rearRightTirePsi": 101,
                },
            ),
            make_asset(
                "DZ-06",
                "DZ-06",
                AssetType.HAUL_TRUCK,
                "Caterpillar",
                "777",
                (40, -2),
                {
                    "speedKph": 4.1,
                    "engineTempC": 76.8,
                    "ambientTemperatureC": 26.9,
                    "tireAgeHours": 301.0,
                    "payloadTonnes": 0,
                    "payloadCapacityTonnes": 220,
                    "fuelLevelPercent": 69,
                    "frontLeftTireC": 75,
                    "frontRightTireC": 74,
                    "rearLeftTireC": 73,
                    "rearRightTireC": 75,
                    "frontLeftTirePsi": 103,
                    "frontRightTirePsi": 102,
                    "rearLeftTirePsi": 103,
                    "rearRightTirePsi": 102,
                },
            ),
            make_asset(
                "GR-01",
                "GR-01",
                AssetType.DRILL,
                "Epiroc",
                "SmartROC",
                (-48, -32),
                {"holeDepthMetres": 12.5, "bitPressureKn": 92, "rotationRpm": 77, "airPressureBar": 18.3},
            ),
        ]

    def list_assets(self) -> list[AssetOverview]:
        return self._assets

    def get_asset(self, asset_id: str) -> AssetOverview | None:
        return next((asset for asset in self._assets if asset.asset.id == asset_id), None)


mock_asset_repository = MockAssetRepository()
